name: example
description: Navbar Router Example
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  navbar_router:
    path: ../
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  badges: ^3.1.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
